"""tenant in out defined

Revision ID: a012c2c4f702
Revises: 0966cae330af
Create Date: 2023-12-02 00:01:33.223483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a012c2c4f702'
down_revision = '0966cae330af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tenants_in',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('details', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('contract_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('contract_id'),
        sa.UniqueConstraint('id')
    )
    op.create_table(
        'tenants_out',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('details', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('contract_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('contract_id'),
        sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenants_out')
    op.drop_table('tenants_in')
    # ### end Alembic commands ###
